name: 'Variable Substitution'
description: 'Apply variable substitution in XML, JSON or YAML files.'
inputs:
  files:
    description: 'comma separated list of files'
    required: true

runs:
  using: 'node24'
  main: 'dist/index.js'